### PR TITLE
Fix #43 (unwanted ADL issues)

### LINKED ISSUE #43: call to 'advance' is ambiguous
I upgraded my boost library from 1.62 to 1.67 (issue remains with 1.68) and now I'm getting "call to 'advance' is ambiguous". After some investigation it looks like [a using statment in boost/iterator/advance.hpp:80](https://github.com/boostorg/iterator/blob/b2adecb951af025698618f19a3c838bd314966dc/include/boost/iterator/advance.hpp#L80) is causing the issue. The problem arises if `advance` is called unqualified, so that ADL triggers. `boost` 1.65 seems to be the first release with this issue.

In my case this means that I cannot use range-v3 (this lib is making the unqualified call to advance) together with boost geometry (this uses boost-iterator's advance function and therefor includes boost/iterator/advance.hpp).

Here is a minimal code example, which causes this issue:
https://godbolt.org/z/rSfeVi

### PR DESCRIPTION
**Pull request by morinmorin**

### CODE REVIEW

**Comment by Lastique** [comment]
Thanks.

**Comment by Lastique** [comment]
@morinmorin I have reverted the change (but not the tests) made by this PR. See 06875a754d6a1e7ed14b761d26020239cf5ad0a2. Feel free to take a look at the problem.

**Comment by morinmorin** [comment]
I submitted PR to Boost.Range (boostorg/range#75), which moves `distance` into ADL barrier namespace and pulls the name via a using-directive.

However, testing on that PR fails now, since Boost.Range's PR and Boost.Iterator's PR need to be applied in sync.

**Comment by Lastique** [comment]
I've reapplied your change and also added a test to check compatibility with `boost::distance` from Boost.Range.

**Comment by pdimov** [comment]
Let me know when this is merged to master so that I can merge Range.

**Pull request merged**
